### ISSUE TITLE
Bot wont disconnect when missing permissions for audio

### ISSUE THREAD

**Issue by imd8594** [Clemens-E/better-airhorn#409]
https://github.com/Clemens-E/better-airhorn/blob/172cf0dad69deca198397c083f0a75be2e021a4b/src/commands/music/play.ts#L57-L72

In the code snippet above, the `play` command already has a voice connection created by `message.ts`, so any `play` command will always connect to the voice chat first. Then the permission checking happens in the `switch (cmd.privacymode)` and will fail if the user does not have permission to play the requested audio clip and return the reject message. This means the `voice.disconnect()` is not being invoked in the instance where you do not have permissions to play an audio clip and the bot is left stuck in the voice channel.

My recommendation is to either modify the `reject()` function to always attempt a `voice.disconnect()` before returning, or to modify the `switch (cmd.privacymode)` to call `voice.disconnect()` before returning reject.

**Comment by qwright10** [comment]
👍 Fixed
