### ISSUE TITLE
make help more accessible

### ISSUE THREAD

**Issue by cnschu** [Clemens-E/better-airhorn#431]
It was quite a pain to find any command for the bot. even the $help command was hard to find.
There should be a simple solution to access the help for any user.

my idea:
* use the status text of the bot to display the $help command, 
* send an text with rudimentary instruction to the user if he messages the bot with any message containing the string "help".

**Comment by Clemens-E** [comment]
Hi, thank you for the feedback.
Sounds like a good idea, I will implement this today, and will later this week pull this over to the [new version](https://github.com/better-airhorn/better-airhorn) that is still in development

**Comment by cnschu** [comment]
thanks
